{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geoprocessor
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/geoprocessoR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f2d33e60519e2bfce5c2fd25bc83d31048089a0588787f9be4421133f6287db0

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
    - r-gdalutils
    - r-rgdal
    - r-sp
    - r-transformer >=1.6.1
  run:
    - r-base
    - r-abind
    - r-gdalutils
    - r-rgdal
    - r-sp
    - r-transformer >=1.6.1

test:
  commands:
    - $R -e "library('geoprocessoR')"           # [not win]
    - "\"%R%\" -e \"library('geoprocessoR')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Geoprocessing tools for climate4R <http://www.meteo.unican.es/climate4R>).
  doc_url: https://github.com/SantanderMetGroup/geoprocessoR
  dev_url: https://github.com/SantanderMetGroup/geoprocessoR
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa


# Package: geoprocessoR
# Depends: R(>= 3.1.0), transformeR(>= 1.6.1),
# Imports: sp, abind, gdalUtils, rgdal
# Suggests: downscaleR, loadeR, loadeR.ECOMS, visualizeR
# Type: Package
# Title: An R package for geoprocessing climate4R data
# Version: 0.2.0
# Date: 2020-01-06
# Author: as.person(c( "Santander Meteorology Group <http://meteo.unican.es> [cph]", "Joaquin Bedia <bediaj@unican.es> [aut]", "Ana Casanueva <ana.casanueva@unican.es> [aut]", "Maialen Iturbide <miturbide@ifca.unican.es> [aut, cre]"))
# Maintainer: Maialen Iturbide <miturbide@ifca.unican.es>
# BugReports: https://github.com/SantanderMetGroup/geoprocesseR/issues
# URL: http://www.meteo.unican.es/climate4r
# Encoding: UTF-8
# Description: Geoprocessing tools for climate4R <http://www.meteo.unican.es/climate4R>).
# License: file LICENSE
# LazyData: true
# RoxygenNote: 6.1.1
